server:
  port: 8082

spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: notificart

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/notificart

kafka:
  url: localhost:9092
  topic: notification-topic